participant "audio/host" as host
participant "drivers/dma" as dma
participant "list/heap" as heap

autoactivate on
-> host : free(dev)
   host -> dma : dma_channel_put(dma, chan)
   host <-- dma

   host -> heap : rfree(...)
   host <-- heap
<-- host
