interface ProcessingModuleInterface {
	uint32_t Process(in_str_buf, out_str_buf)
	void Reset()
	void SetProcessingMode(ProcessingMode proc_mod)
	ProcessingMode GetProcessingMode()
	ErrorCode SetConfiguration(uint32_t config_id,
		ConfigurationFragmentPosition fragment_position,
		uint32_t data_offset_size,
		const uint8_t* fragment_buffer,
		size_t fragment_size,
		uint8_t* response,
		size_t& response_size)
	ErrorCode GetConfiguration()
}

enum ProcesingMode {
	NORMAL,
	BYPASS
}

enum ErrorCode
